name: Automated Version Bump
description: Automated version bump for npm packages.
runs:
  using: node12
  main: index.js
branding:
  icon: chevron-up
  color: blue
inputs:
  tag-prefix:
    description: 'Prefix that is used for the git tag'
    default: ''
    required: false
  PACKAGEJSON_DIR:
    description: 'Custom dir to the package.json file'
    default: ''
    required: false
  target-branch:
    description: 'A separate branch to perform the version bump on'
    default: ''
    required: false
  commit-message:
    description: 'Set a custom commit message for version bump commit'
    default: ''
    required: false
  skip-tag:
    description: 'Avoid to add a TAG to the version update commit'
    default: 'false'
    required: false
  skip-push:
    description: 'If true, skip pushing any commits or tags created after the version bump'
    default: false
    required: false
outputs:
  newTag:
    description: 'The newly created tag'
