name: 'Bump Build Number'

on:
  push:
    branches:
      - 'main'

jobs:
  bump-version:
    name: 'Bump buildNumber on main'
    runs-on: ubuntu-latest

    steps:
      - name: Wait for 30 seconds
        run: sleep 30
        
      - name: 'Checkout source code'
        uses: 'actions/checkout@v3'
        with:
          ref: ${{ github.ref }}
      - name: 'cat package.json'
        run: cat ./package.json
      - name: 'Automated Build Number Bump'
        id: buildNumber-bump
        uses: 'Cdimock/gh-action-bump-buildNumber@main'
        with:
          tag-prefix: 'build/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'cat package.json'
        run: cat ./package.json
